# Generated by Django 4.2.2 on 2023-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_year',
        ),
        migrations.AddField(
            model_name='anime',
            name='year_first_episode',
            field=models.CharField(default=2017, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='year_last_episode',
            field=models.CharField(default=2017, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_rating',
            field=models.CharField(max_length=5),
        ),
    ]
