# Generated by Django 4.2.2 on 2023-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_anime_anime_year_anime_year_first_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
