# Generated by Django 4.2.2 on 2023-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_anime_anime_image_alter_anime_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
